version: '3.8'

services:
  hadoop_docker:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ssh_volume:/home/glauco/.ssh
      - hadoop_volume:/opt/hadoop
      - tmp_volume:/opt/tmp
      - logs_volume:/opt/logs
      - staging_volume:/home/glauco/staging
      - jupyter_volume:/home/glauco/.jupyter
      - python_volume:/usr/lib/python3.10

volumes:
  ssh_volume:
  hadoop_volume:
  tmp_volume:
  logs_volume:
  staging_volume:
  jupyter_volume:
  python_volume: